'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowUpRight, Check, Clock3, Heart, Leaf, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Star, X } from 'lucide-react'

const meals = [
  ['Mon', 'Dal Tadka · Aloo Gobi', 'Jeera rice & 4 rotis'],
  ['Tue', 'Rajma Masala · Lauki', 'Steamed rice & 4 rotis'],
  ['Wed', 'Kadhi Pakoda · Bhindi', 'Jeera rice & 4 rotis'],
  ['Thu', 'Chole Masala · Mix Veg', 'Pulao & 4 rotis'],
  ['Fri', 'Paneer Butter Masala · Dal', 'Rice & 4 rotis'],
]

const plans = [
  { name: 'Single Meal', price: '₹90', detail: 'A hearty, freshly cooked lunch or dinner.', features: ['Freshly cooked daily', 'Free delivery in service areas', 'Salad, pickle & sweet bite'] },
  { name: 'Monthly Lunch', price: '₹2,199', detail: '26 wholesome meals delivered to your door.', popular: true, features: ['Freshly cooked daily', 'Free delivery in service areas', 'Skip days anytime', 'Best value for money'] },
  { name: 'Monthly Combo', price: '₹3,999', detail: 'Lunch and dinner sorted for the whole month.', features: ['52 meals per month', 'Free delivery in service areas', 'Salad, pickle & sweet bite', 'Skip days anytime'] },
]

const whatsapp = 'https://wa.me/919876543210?text=Hi%20Aradhana%2C%20I%20want%20to%20order%20tiffin%20meals'

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeDay, setActiveDay] = useState('Mon')

  return (
    <main className="min-h-screen overflow-hidden bg-[#fffaf3] text-[#2b211b] selection:bg-[#f6c453]">
      <div className="bg-gradient-to-r from-[#2e6a43] to-[#1f4a2f] px-5 py-2.5 text-center text-[11px] font-medium tracking-[0.16em] text-[#f8f0dd] uppercase sm:text-xs">Freshly cooked every morning · Trusted by 500+ families · Delivering across Indore</div>
      <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-12">
        <a href="#top" className="flex items-center gap-3" aria-label="Aradhana Tiffin Services home"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#e66f37] text-[#fffaf3]"><Leaf size={21} /></span><span className="leading-[0.95]"><span className="block font-serif text-xl font-bold">Aradhana</span><span className="mt-1 block text-[9px] font-bold tracking-[0.25em] text-[#9a6a47] uppercase">Tiffin Services</span></span></a>
        <div className="hidden items-center gap-8 text-sm font-semibold text-[#6b5a4e] md:flex"><a href="#menu" className="hover:text-[#e66f37]">This week&apos;s menu</a><a href="#plans" className="hover:text-[#e66f37]">Plans</a><a href="#why-us" className="hover:text-[#e66f37]">Why Aradhana</a><a href="#contact" className="rounded-full bg-[#e66f37] px-5 py-3 text-white shadow-lg">Get a tiffin <ArrowUpRight className="ml-1 inline" size={15} /></a></div>
        <button className="rounded-full bg-[#f5ead7] p-3 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        {menuOpen && <div className="absolute top-[78px] right-5 left-5 rounded-2xl border border-[#eadbc7] bg-[#fffaf3] p-4 shadow-xl md:hidden"><div className="grid gap-2 text-sm font-semibold"><a onClick={() => setMenuOpen(false)} href="#menu" className="rounded-lg px-3 py-2 hover:bg-[#f5ead7]">This week&apos;s menu</a><a onClick={() => setMenuOpen(false)} href="#plans" className="rounded-lg px-3 py-2 hover:bg-[#f5ead7]">Plans</a><a onClick={() => setMenuOpen(false)} href="#why-us" className="rounded-lg px-3 py-2 hover:bg-[#f5ead7]">Why Aradhana</a><a onClick={() => setMenuOpen(false)} href="#contact" className="rounded-lg bg-[#e66f37] px-3 py-2 text-white">Get a tiffin</a></div></div>}
      </nav>

      <section id="top" className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-8 sm:px-8 lg:grid-cols-[0.95fr_1.05fr] lg:gap-20 lg:px-12 lg:pb-20 lg:pt-16">
        <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#e8d7bd] bg-[#fff7e9] px-4 py-2.5 text-xs font-bold text-[#8d5b35]"><Sparkles size={15} className="text-[#e6a22f]" /> Authentic home-cooked meals</div><h1 className="max-w-xl font-serif text-[3.2rem] font-bold leading-[1.05] tracking-[-0.02em] sm:text-5xl lg:text-[4.5rem]">Ghar jaisa khana.<br /><em className="font-normal text-[#e66f37]">Har din, sab ke liye.</em></h1><p className="mt-6 max-w-lg text-base leading-8 text-[#725f52] sm:text-lg">Wholesome vegetarian meals prepared fresh daily with premium ingredients. No preservatives, no compromises, just pure nourishment delivered across Indore.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#plans" className="inline-flex items-center justify-center rounded-full bg-[#e66f37] px-7 py-3.5 text-sm font-bold text-white shadow-lg transition-all hover:bg-[#d45f27] hover:shadow-xl">Explore meal plans <ArrowUpRight className="ml-2" size={16} /></a><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-full border-2 border-[#e66f37] px-7 py-3.5 text-sm font-bold text-[#e66f37] transition-colors hover:bg-[#fff3d8]"><MessageCircle className="mr-2" size={18} /> Order on WhatsApp</a></div><div className="mt-11 flex items-center gap-4 border-t border-[#eadbc7] pt-7"><div className="flex -space-x-3"><span className="flex h-10 w-10 items-center justify-center rounded-full border-3 border-[#fffaf3] bg-[#e7b38b] text-xs font-bold text-white">RK</span><span className="flex h-10 w-10 items-center justify-center rounded-full border-3 border-[#fffaf3] bg-[#b8ceae] text-xs font-bold text-white">AV</span><span className="flex h-10 w-10 items-center justify-center rounded-full border-3 border-[#fffaf3] bg-[#e8c977] text-xs font-bold text-white">PM</span></div><div><div className="flex items-center gap-1 text-sm font-bold"><Star size={14} className="fill-[#f59e0b] text-[#f59e0b]" /> 4.9/5 customer rating</div><p className="text-xs text-[#8d7868]">500+ happy families trust us daily</p></div></div></div>
        <div className="relative"><div className="absolute -inset-4 rounded-[2.5rem] bg-[#f4d8a7]/40 blur-2xl" /><div className="relative overflow-hidden rounded-[2.5rem] border-8 border-white bg-[#f5ead7] shadow-2xl"><Image src="/images/hero-meal.png" alt="A fresh vegetarian Aradhana tiffin meal" width={800} height={800} className="aspect-square object-cover" priority /></div><div className="absolute -bottom-5 -left-4 rounded-2xl bg-white px-4 py-3 shadow-xl sm:left-4"><p className="text-xs font-bold text-[#2e6a43]">Made fresh every morning</p><p className="mt-1 text-[11px] text-[#8d7868]">Packed with care in Indore</p></div></div>
      </section>

      <section className="border-y border-[#eadbc7] bg-[#f5ead7]/55 px-5 py-5 sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-3 text-center text-xs font-bold tracking-wide text-[#725f52] uppercase sm:justify-between"><span className="flex items-center gap-2"><Leaf size={16} className="text-[#2e6a43]" /> Pure vegetarian</span><span className="flex items-center gap-2"><Heart size={16} className="text-[#e66f37]" /> Cooked with love</span><span className="flex items-center gap-2"><MapPin size={16} className="text-[#d3912d]" /> Across Indore</span><span className="flex items-center gap-2"><Clock3 size={16} className="text-[#2e6a43]" /> On-time delivery</span></div></section>

      <section id="menu" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-xs font-bold tracking-[0.2em] text-[#e66f37] uppercase">Rotating weekly menu</p><h2 className="font-serif text-4xl font-bold tracking-[-0.04em] sm:text-5xl">This week&apos;s <span className="font-normal text-[#2e6a43]">delicious offerings</span></h2></div><p className="max-w-sm text-sm leading-6 text-[#8d7868]">Carefully planned seasonal menus that keep your everyday meals exciting.</p></div><div className="grid gap-4 md:grid-cols-5">{meals.map(([day, dish, note]) => <button key={day} onClick={() => setActiveDay(day)} className={`rounded-2xl border p-5 text-left transition-all duration-200 ${activeDay === day ? 'border-[#2e6a43] bg-[#2e6a43] text-white shadow-lg' : 'border-[#eadbc7] bg-white hover:-translate-y-1 hover:border-[#b6cdb4] hover:shadow-md'}`}><div className={`mb-3 text-xs font-bold tracking-[0.16em] uppercase ${activeDay === day ? 'text-[#e1e9c4]' : 'text-[#a17b5c]'}`}>{day}</div><div className="font-serif text-lg font-bold leading-tight">{dish}</div><div className={`mt-2 text-xs leading-5 ${activeDay === day ? 'text-[#d3e0ce]' : 'text-[#8d7868]'}`}>{note}</div></button>)}</div><div className="mt-8 flex items-start gap-4 rounded-2xl border border-[#ffe4c4] bg-gradient-to-r from-[#fff3d8] to-[#fffae6] p-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#e8c15b] font-serif font-bold text-[#75512e]">{activeDay.charAt(0)}</div><div><p className="text-sm font-bold text-[#75512e]">What&apos;s included in every tiffin</p><p className="mt-1 text-xs text-[#8d7868]">Fresh salad · Tangy pickle · Sweet treat · Rice · Four wholesome rotis</p></div></div></section>

      <section id="why-us" className="bg-gradient-to-b from-[#2e6a43] to-[#1f4a2f] px-5 py-20 text-[#fffaf3] sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1fr_1.2fr] lg:items-center"><div><p className="mb-4 text-xs font-bold tracking-[0.2em] text-[#c8e6b8] uppercase">Why choose Aradhana</p><h2 className="max-w-md font-serif text-4xl font-bold leading-tight sm:text-5xl">Authentic comfort, every single day</h2><p className="mt-6 max-w-md leading-8 text-[#d3e0ce]">We bring the warmth and nutrition of home-cooked food to busy Indore families, one carefully prepared meal at a time.</p></div><div className="grid gap-4 sm:grid-cols-2">{[['Simple ingredients', 'No shortcuts or preservatives. Just pantry staples you can trust.', Leaf], ['Made with care', 'Every meal is prepared as if it were for our own family.', Heart], ['Always hygienic', 'Clean kitchens, careful packing and fresh delivery every day.', ShieldCheck], ['Made for Indore', 'Local flavours and reliable delivery across your neighbourhood.', MapPin]].map(([title, text, Icon], index) => <div key={title as string} className={`rounded-3xl border border-white/15 bg-white/10 p-7 backdrop-blur-sm ${index % 2 ? 'sm:translate-y-8' : ''}`}><Icon className="mb-6 text-[#f6c453]" size={30} /><h3 className="font-serif text-2xl font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#d3e0ce]">{text as string}</p></div>)}</div></div></section>

      <section id="plans" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="text-center"><p className="mb-4 text-xs font-bold tracking-[0.2em] text-[#e66f37] uppercase">Flexible meal plans</p><h2 className="font-serif text-4xl font-bold tracking-[-0.04em] sm:text-5xl">Find your perfect <span className="font-normal text-[#e66f37]">meal plan</span></h2><p className="mx-auto mt-5 max-w-lg text-[#8d7868]">Start with one meal or make Aradhana part of your everyday routine.</p></div><div className="mx-auto mt-14 grid max-w-6xl gap-6 lg:grid-cols-3">{plans.map((plan) => <div key={plan.name} className={`relative rounded-3xl border p-8 transition-all hover:shadow-xl ${plan.popular ? 'border-[#e66f37] bg-[#fff3d8] shadow-lg lg:-translate-y-4' : 'border-[#eadbc7] bg-white'}`}>{plan.popular && <span className="absolute -top-4 left-1/2 -translate-x-1/2 rounded-full bg-[#e66f37] px-4 py-1.5 text-[11px] font-bold tracking-wider text-white uppercase shadow-md">Most popular</span>}<h3 className="mt-2 font-serif text-2xl font-bold">{plan.name}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-[#8d7868]">{plan.detail}</p><div className="mt-7"><span className="font-serif text-5xl font-bold">{plan.price}</span>{plan.name !== 'Single Meal' && <span className="ml-2 text-sm text-[#8d7868]">/ month</span>}</div><a href={whatsapp} target="_blank" rel="noopener noreferrer" className={`mt-8 flex w-full items-center justify-center rounded-full px-5 py-3.5 text-sm font-bold transition-all ${plan.popular ? 'bg-[#e66f37] text-white hover:bg-[#d45f27]' : 'bg-[#f5ead7] text-[#523b2b] hover:bg-[#eee4c3]'}`}>Choose this plan <ArrowUpRight className="ml-2" size={15} /></a><ul className="mt-8 space-y-3 border-t border-[#eadbc7] pt-7 text-sm text-[#6f5c4d]">{plan.features.map((feature) => <li key={feature} className="flex gap-3"><Check size={18} className="shrink-0 text-[#2e6a43]" /> {feature}</li>)}</ul></div>)}</div></section>

      <section id="contact" className="relative mx-5 mb-10 overflow-hidden rounded-3xl bg-gradient-to-r from-[#e66f37] via-[#d95e2d] to-[#c65025] px-6 py-14 text-center text-white shadow-2xl sm:mx-8 lg:mx-auto lg:max-w-7xl lg:px-16 lg:py-20"><div className="relative z-10"><p className="mb-4 text-xs font-bold tracking-[0.2em] text-[#ffe1a7] uppercase">Ready to taste home-style food?</p><h2 className="font-serif text-4xl font-bold sm:text-5xl">Order your first meal today</h2><p className="mx-auto mt-5 max-w-md text-lg text-[#ffe4ce]">Join 500+ families enjoying fresh, wholesome meals. Your first order is just a WhatsApp away.</p><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center rounded-full bg-[#fffaf3] px-8 py-4 text-base font-bold text-[#d46031] shadow-lg transition-all hover:bg-white"><MessageCircle className="mr-2" size={20} /> Order on WhatsApp</a><a href="tel:+919876543210" className="inline-flex items-center justify-center rounded-full border-2 border-white px-8 py-4 text-base font-bold text-white hover:bg-white/10"><Phone className="mr-2" size={20} /> Call now</a></div><div className="mt-10 flex flex-col items-center justify-center gap-3 border-t border-white/20 pt-8 text-sm text-[#ffe4ce] sm:flex-row"><MapPin size={18} /> Serving Vijay Nagar, Palasia, Rau & nearby areas <span className="hidden sm:inline">·</span> <Clock3 size={18} /> 7:30 AM - 1:30 PM delivery</div></div></section>

      <footer className="border-t border-[#eadbc7] bg-[#fffaf3] px-5 py-12 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-8 md:grid-cols-2"><div><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e66f37] text-[#fffaf3]"><Leaf size={20} /></span><p className="font-serif text-lg font-bold">Aradhana Tiffin Services</p></div><p className="mt-4 max-w-sm text-sm leading-6 text-[#8d7868]">Bringing the warmth and authenticity of home-cooked meals to Indore families since 2022.</p></div><div><p className="mb-4 font-bold text-[#523b2b]">Get in touch</p><p className="text-sm leading-7 text-[#8d7868]">Vijay Nagar, Indore<br />+91 9876 543 210<br />Message us on WhatsApp</p></div></div><div className="mt-8 flex flex-col gap-4 border-t border-[#eadbc7] pt-8 text-center text-xs text-[#8d7868] sm:flex-row sm:items-center sm:justify-between sm:text-left"><p>© 2024 Aradhana Tiffin Services. Crafted with care in Indore.</p><span className="flex items-center justify-center gap-2">Made for your home <Heart size={14} className="fill-[#e66f37] text-[#e66f37]" /></span></div></div></footer>
      <div className="fixed bottom-6 right-6 z-30 sm:hidden"><a href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Order via WhatsApp" className="flex h-16 w-16 items-center justify-center rounded-full bg-[#2e6a43] text-white shadow-2xl transition-all hover:scale-110"><MessageCircle size={28} /></a></div>
    </main>
  )
}
